name: test-environment
dependencies:
  - python=2.7
  - numpy
  - scipy
  - matplotlib
  - pytest
  - h5py
  - pyzmq
  - pep8
  - pytest
  - mpi4py 
  - pil
  - pip:
    - pytest-cov
    - coveralls


